# docker compose up -d redis mongodb mysql postgres rabbitmq elasticsearch kibana notifications auth gateway
version: '3.9'
services:
  redis:
    container_name: 'redis_container'
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
    networks:
      - elastic
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/data:/data/db
    networks:
      - elastic
  mysql:
    container_name: mysql_container
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=ashish
      - MYSQL_DATABASE=job_app_auth
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PASSWORD=pass
    ports:
      - 3306:3306
    volumes:
      - ./docker-volumes/mysql_db:/var/lib/mysql
    networks:
      - elastic
  postgres:
    container_name: postgres_container
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=ashish
      - POSTGRES_DB=job_app_reviews
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=ashish
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      #AMQP Protocol port
      - 5672:5672
      # Management UI
      - 15672:15672
    networks:
      - elastic
  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    restart: always
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
      xpack.security.enabled: "true"
      xpack.security.authc.api_key.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
      xpack.security.enrollment.enabled: "true"
      xpack.security.authc.token.enabled: "true"
      ELASTIC_PASSWORD: admin1234
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./docker-volumes/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:8.11.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana
      - ELASTICSEARCH_SERVICEACCOUNT_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2FzaGlzaC1qb2Ita2liYW5hOi1ad0ZndnQ1Um42cmNhTTFJT1V3Zmc
      - XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
  notifications:
    container_name: notification_container
    build:
      context: ../server/ashish-notification-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4001:4001
    env_file: ../server/ashish-notification-service/.env
    environment:
      - ENABLE_APM=0
      - NODE_ENV=development
      - CLIENT_URL= http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://ashish:pass@rabbitmq_container:5672
      - SENDER_EMAIL=edmund90@ethereal.email
      - SENDER_EMAIL_PASSWORD=bWcYU9qje1fCq6H63a
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - rabbitmq
    networks:
      - elastic
  auth:
    container_name: auth_container
    build:
      context: ../server/ashish-auth-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4002:4002
    env_file: ../server/ashish-auth-service/.env
    environment:
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=28da9c8be478ba1117496f68355b1831
      - JWT_TOKEN=eea260b9743ba3b77e2798c6a3b386b2
      - API_GATEWAY_URL=http://gateway_container:4000
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://ashish:pass@rabbitmq_container:5672
      - MYSQL_DB=mysql://ashish:pass@mysql_container:3306/job_app_auth
      - CLOUD_NAME=dreqvwyyh
      - CLOUD_API_KEY=829487497375964
      - CLOUD_API_SECRET=2c_pXWbGlUDcK3Wm5QbKcJN8cIM
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - rabbitmq
      - mysql
    networks:
      - elastic
  gateway:
    container_name: gateway_container
    build:
      context: ../server/ashish-gateway-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:4000
    env_file: ../server/ashish-notification-service/.env
    environment:
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=28da9c8be478ba1117496f68355b1831
      - JWT_TOKEN=eea260b9743ba3b77e2798c6a3b386b2  
      - NODE_ENV=development
      - SECRET_KEY_ONE=4915a91f24b949f894b4307536022956
      - SECRET_KEY_TWO=388beb30d68f367ffbbaa3fcf3526dc7
      - CLIENT_URL=http://localhost:3000
      - AUTH_BASE_URL=http://auth_container:4002
      - USERS_BASE_URL=http://localhost:4003
      - GIG_BASE_URL=http://localhost:4004
      - MESSAGE_BASE_URL=http://localhost:4005
      - ORDER_BASE_URL=http://localhost:4006
      - REVIEW_BASE_URL=http://localhost:4007
      - REDIS_HOST=redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - rabbitmq
    networks:
      - elastic

networks:
  elastic:
    name: elastic


